=== tloinuy/opencpi-opencv/opencpi/test/sred/rcc-file-io/output/properties.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!ELEMENT properties
     	 ( description?
     	 , ( simple | simplesequence | test | struct | structsequence )+
       )> 

<!ELEMENT simple 
	( description?
	, value?
	, units?
	, range?
	, enumerations?
	, kind*
	, action?
	)>
<!ATTLIST simple
	id		ID	#REQUIRED
	type	( boolean	| char	| double | float | short	| long	| objref | octet
         | string	| ulong	| ushort )		#REQUIRED
	name	CDATA	#IMPLIED
	mode	( readonly	| readwrite | writeonly)	"readwrite">

<!ELEMENT description (#PCDATA)>

<!ELEMENT value (#PCDATA)>

<!ELEMENT units (#PCDATA)>

<!ELEMENT range EMPTY>
<!ATTLIST range
	min		CDATA	#REQUIRED
	max		CDATA	#REQUIRED>

<!ELEMENT enumerations
	( enumeration+
	)>

<!ELEMENT enumeration EMPTY>
<!ATTLIST enumeration
	label	CDATA	#REQUIRED
	value	CDATA	#IMPLIED>

<!ELEMENT kind EMPTY>
<!ATTLIST kind
	kindtype	(allocation | configure | test | execparam | factoryparam) "configure">

<!ELEMENT action EMPTY>
<!ATTLIST action
	type	( eq  | ne | gt  |  lt | ge | le | external ) "external">

<!ELEMENT simplesequence 
	( description?
	, values?
	, units?
	, range?
	, kind*
	, action?
	)>
<!ATTLIST simplesequence
	id	ID						#REQUIRED
	type  ( boolean | char   | double | float
	      | short  | long   | objref | octet
	      | string | ulong  | ushort )	#REQUIRED
	name	CDATA						#IMPLIED
	mode	(readonly | readwrite | writeonly)	"readwrite">

<!ELEMENT values
	( value+ 
	)>

<!ELEMENT test 
	( description
	, inputvalue?
	, resultvalue
	)>
<!ATTLIST test
	id		CDATA #REQUIRED>

<!ELEMENT inputvalue
	( simple+
	)>

<!ELEMENT resultvalue
	( simple+
	)>

<!ELEMENT struct 
	( description?
	, simple+
	, configurationkind?
	)>
<!ATTLIST struct
	id		ID	#REQUIRED
	name	CDATA	#IMPLIED
	mode	(readonly | readwrite | writeonly)  "readwrite">
         
<!ELEMENT configurationkind EMPTY>
<!ATTLIST configurationkind
	kindtype	(configure | factoryparam)	"configure">

<!ELEMENT structsequence
	( description?
	, structvalue+
	, configurationkind?
	)>
<!ATTLIST structsequence
	id       	ID	#REQUIRED
	structrefid CDATA	#REQUIRED
	name		CDATA	#IMPLIED
	mode		(readonly | readwrite | writeonly)  "readwrite">
		
<!ELEMENT structvalue
	(simpleref+	        
	)>
		
<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid 	CDATA	#REQUIRED
	value 	CDATA	#REQUIRED>

=== tloinuy/opencpi-opencv/opencpi/tools/local/tester/file_io_workers/model/FileSourceComponent.prf.xml
<?xml version="1.0" encoding="us-ascii"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE properties SYSTEM "properties.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.4.7
    http://www.zeligsoft.com
-->
<properties>
    <description />
    <simple id="DCE:3895f3d9-1c07-4ca8-afcf-1e786e6e358f" type="string" name="portName" mode="readwrite">
        <description>max_string_size=255</description>
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:0c2709f8-2b3f-463f-bfe4-f7c25fa7031a" type="string" name="fileName" mode="readwrite">
        <description>max_string_size=255</description>
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:82f4c491-8a72-4ba6-9e3d-8265923a76ba" type="ulong" name="bytesPerPacket" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:60d83bb4-6e60-4a70-8c22-34bc280b5f5b" type="ulong" name="offset" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:08bf13a6-1b90-43aa-9178-986b355bdb4d" type="ulong" name="errnoValue" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:3275d91d-492b-499c-bebb-0ae3b4e8c506" type="boolean" name="atEof" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:7e77884c-d9b1-4260-a689-43c63c17d3da" type="boolean" name="verbose" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
</properties>

<!-- Model validation produced warning or error messages.
     Use this generated XML for model debugging only. -->

=== tloinuy/opencpi-opencv/opencpi/test/sred/rcc-file-io/output/GenericAssemblyControllerComponent.prf.xml
<?xml version="1.0" encoding="us-ascii"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE properties SYSTEM "properties.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.4.6
    http://www.zeligsoft.com
-->
<properties>
    <description />
    <simple id="DCE:50bd03ab-33b4-485f-9af4-650c2bd4e2a2" type="string" name="Source.fileName" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:d866ff26-13c6-4ce4-88f2-32eda10cb515" type="string" name="Tee.fileName" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:e137c8da-6ddb-481e-a56e-448332334df9" type="string" name="Sink.fileName" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
</properties>

=== tloinuy/opencpi-opencv/opencpi/test/sred/rcc-file-io/output/FileSourceComponent.prf.xml
<?xml version="1.0" encoding="us-ascii"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE properties SYSTEM "properties.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.4.6
    http://www.zeligsoft.com
-->
<properties>
    <description />
    <simple id="DCE:be8cbe84-70ca-4117-970f-3b2cc24450c2" type="string" name="fileName" mode="readwrite">
        <description>max_string_size=256</description>
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:52d9ebfa-4102-4df6-a8b8-158d9811c528" type="ulong" name="bytesPerPacket" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:9a429aa8-071f-4d55-ac40-c087bb51b16a" type="ulong" name="offset" mode="readonly">
        <kind kindtype="configure" />
    </simple>
    <test id="1245111881">
        <description />
        <resultvalue>
            <simple id="DCE:d5462d5b-b84a-4e12-a6a6-449ecec67b77" type="ulong" name="errnoValue" mode="readwrite">
                <kind kindtype="test" />
            </simple>
        </resultvalue>
    </test>
</properties>

=== tloinuy/opencpi-opencv/opencpi/tools/local/tester/file_io_workers/model/FileSinkComponent.prf.xml
<?xml version="1.0" encoding="us-ascii"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE properties SYSTEM "properties.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.4.7
    http://www.zeligsoft.com
-->
<properties>
    <description />
    <simple id="DCE:4ed23973-0acf-4937-a4c5-1050f2aa1aef" type="string" name="portName" mode="readwrite">
        <description>max_string_size=255</description>
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:6c7552fd-1b80-46ae-95bc-a84e7ae9ef1f" type="string" name="fileName" mode="readwrite">
        <description>max_string_size=255</description>
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:a7c775aa-d0df-48b1-b697-752fb3ca33e1" type="ulong" name="offset" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:2b7676e3-172e-4be8-999a-7a779e21051e" type="ulong" name="errnoValue" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
    <simple id="DCE:f377e750-5ada-4506-b6d7-8e18dea04405" type="boolean" name="verbose" mode="readwrite">
        <kind kindtype="configure" />
    </simple>
</properties>

<!-- Model validation produced warning or error messages.
     Use this generated XML for model debugging only. -->
