=== tloinuy/opencpi-opencv/opencpi/test/sred/rcc-file-io/output/softwareassembly.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!ELEMENT softwareassembly
	( description?
	, componentfiles
	, partitioning
	, assemblycontroller
	, connections?
	, externalports?
	)>
<!ATTLIST softwareassembly
	id		ID		#REQUIRED
	name	CDATA	#IMPLIED
	version	CDATA	#IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT componentfiles 
	( componentfile+
	)>

<!ELEMENT componentfile
	( localfile 
	)>
<!ATTLIST componentfile
	id		ID	#REQUIRED
	type	CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT partitioning 
	( componentplacement |  hostcollocation
	)+>

<!ELEMENT componentplacement 
	( componentfileref
	, componentinstantiation+
	)>

<!ELEMENT componentfileref  EMPTY>
<!ATTLIST componentfileref
	refid		CDATA	#REQUIRED>

<!ELEMENT componentinstantiation
	( usagename?
	, componentproperties?
	, findcomponent?
	)>
<!ATTLIST componentinstantiation
	id		ID 	#REQUIRED>

<!ELEMENT usagename (#PCDATA)>

<!ELEMENT componentproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT findcomponent
	( componentresourcefactoryref
	| namingservice
	)>

<!ELEMENT componentresourcefactoryref
	( resourcefactoryproperties?
	)>
<!ATTLIST componentresourcefactoryref 
	refid		CDATA	#REQUIRED>

<!ELEMENT resourcefactoryproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	(simpleref+        
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
         )>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	(simpleref+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

<!ELEMENT hostcollocation
	( componentplacement)+>

<!ATTLIST hostcollocation
	id		ID	#IMPLIED
	name		CDATA	#IMPLIED>

<!ELEMENT assemblycontroller
	( componentinstantiationref
	)>

<!ELEMENT connections
	( connectinterface*
	)>

<!ELEMENT connectinterface
	( usesport
	, ( providesport | componentsupportedinterface | findby)
	)>
<!ATTLIST connectinterface
	id 		ID	#IMPLIED>

<!ELEMENT usesport
	( usesidentifier
	, (componentinstantiationref
	   | devicethatloadedthiscomponentref
	   | deviceusedbythiscomponentref
	   | findby
	   )
	)>

<!ELEMENT usesidentifier (#PCDATA)>

<!ELEMENT componentinstantiationref EMPTY>
<!ATTLIST componentinstantiationref 
	refid		CDATA	#REQUIRED>

<!ELEMENT findby
	( namingservice
	| domainfinder
	)>

<!ELEMENT namingservice EMPTY>
<!ATTLIST namingservice
	name 		CDATA	#REQUIRED>

<!ELEMENT domainfinder EMPTY>
<!ATTLIST domainfinder
	type		(filemanager |log | eventchannel | namingservice)	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT devicethatloadedthiscomponentref EMPTY>
<!ATTLIST devicethatloadedthiscomponentref 
	refid		CDATA	#REQUIRED>

<!ELEMENT deviceusedbythiscomponentref EMPTY>
<!ATTLIST deviceusedbythiscomponentref 
	refid	CDATA	#REQUIRED
usesrefid	CDATA	#REQUIRED>

<!ELEMENT providesport
	( providesidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | findby)
	)>

<!ELEMENT providesidentifier (#PCDATA)>

<!ELEMENT componentsupportedinterface
	( supportedidentifier
	, ( componentinstantiationref
	  | findby)
	)>

<!ELEMENT supportedidentifier (#PCDATA)>

<!ELEMENT externalports 
	(port+
	)>

<!ELEMENT port
	( description?
	, (usesidentifier | providesidentifier | supportedidentifier)
	, componentinstantiationref
	)>

=== tloinuy/opencpi-opencv/opencpi/test/sred/rcc-file-io/output/FileCopy.sad.xml
<?xml version="1.0" encoding="us-ascii"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE softwareassembly SYSTEM "softwareassembly.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.4.6
    http://www.zeligsoft.com
-->
<softwareassembly id="DCE:fdfc21d4-505a-4494-bae1-93036020ee47" name="FileCopy">
    <componentfiles>
        <componentfile id="FileSourceFile_970f6c6b-fe2d-4de7-8a9b-e4d7ebd3ccd1" type="Software Package Descriptor">
            <localfile name="FileSource.spd.xml" />
        </componentfile>
        <componentfile id="FileSinkFile_29aa1166-d2fe-407a-b8e4-8d3ab687f9a3" type="Software Package Descriptor">
            <localfile name="FileSink.spd.xml" />
        </componentfile>
        <componentfile id="GenericAssemblyControllerFile_70aad05d-b3a4-407c-afc7-ef7ae8ba31a0" type="Software Package Descriptor">
            <localfile name="GenericAssemblyController.spd.xml" />
        </componentfile>
        <componentfile id="FileTeeFile_d961ac6f-92b6-4d2b-965f-4b2658e5ea63" type="Software Package Descriptor">
            <localfile name="FileTee.spd.xml" />
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="FileSourceFile_970f6c6b-fe2d-4de7-8a9b-e4d7ebd3ccd1" />
            <!--[Component filesource1]-->
            <componentinstantiation id="DCE:56987519-2acd-4247-ac08-ef2c6de48271">
                <usagename>filesource1</usagename>
                <findcomponent>
                    <namingservice name="filesource1" />
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="FileSinkFile_29aa1166-d2fe-407a-b8e4-8d3ab687f9a3" />
            <!--[Component filesink1]-->
            <componentinstantiation id="DCE:8b55efc7-4625-472b-ac12-9a3594cff6a6">
                <usagename>filesink1</usagename>
                <findcomponent>
                    <namingservice name="filesink1" />
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="GenericAssemblyControllerFile_70aad05d-b3a4-407c-afc7-ef7ae8ba31a0" />
            <!--[Component filecopyassemblycontroller1]-->
            <componentinstantiation id="DCE:bd0ca14f-c286-4433-9bb8-de84b7f6d5db">
                <usagename>filecopyassemblycontroller1</usagename>
                <findcomponent>
                    <namingservice name="filecopyassemblycontroller1" />
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="FileTeeFile_d961ac6f-92b6-4d2b-965f-4b2658e5ea63" />
            <!--[Component filetee1]-->
            <componentinstantiation id="DCE:9a5259f4-459a-4413-b1b7-db699ab45413">
                <usagename>filetee1</usagename>
                <findcomponent>
                    <namingservice name="filetee1" />
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <assemblycontroller>
        <!--[Assembly Controller filecopyassemblycontroller1]-->
        <componentinstantiationref refid="DCE:bd0ca14f-c286-4433-9bb8-de84b7f6d5db" />
    </assemblycontroller>
    <connections>
        <!--Connection between [Component filecopyassemblycontroller1, Port Source] and [Component filesource1, Port resource1]-->
        <connectinterface id="DCE:8fdebe8d-5cf7-4056-a888-b95bd470fc30">
            <usesport>
                <usesidentifier>Source</usesidentifier>
                <componentinstantiationref refid="DCE:bd0ca14f-c286-4433-9bb8-de84b7f6d5db" />
            </usesport>
            <componentsupportedinterface>
                <supportedidentifier>IDL:CF/Resource:1.0</supportedidentifier>
                <componentinstantiationref refid="DCE:56987519-2acd-4247-ac08-ef2c6de48271" />
            </componentsupportedinterface>
        </connectinterface>
        <!--Connection between [Component filecopyassemblycontroller1, Port Sink] and [Component filesink1, Port resource1]-->
        <connectinterface id="DCE:a6ed2639-f451-48e3-b48f-1a16a4f4b9dc">
            <usesport>
                <usesidentifier>Sink</usesidentifier>
                <componentinstantiationref refid="DCE:bd0ca14f-c286-4433-9bb8-de84b7f6d5db" />
            </usesport>
            <componentsupportedinterface>
                <supportedidentifier>IDL:CF/Resource:1.0</supportedidentifier>
                <componentinstantiationref refid="DCE:8b55efc7-4625-472b-ac12-9a3594cff6a6" />
            </componentsupportedinterface>
        </connectinterface>
        <!--Connection between [Component filecopyassemblycontroller1, Port Tee] and [Component filetee1, Port resource1]-->
        <connectinterface id="DCE:5e9d2d5f-5072-44fa-8558-8cdf5e2ce204">
            <usesport>
                <usesidentifier>Tee</usesidentifier>
                <componentinstantiationref refid="DCE:bd0ca14f-c286-4433-9bb8-de84b7f6d5db" />
            </usesport>
            <componentsupportedinterface>
                <supportedidentifier>IDL:CF/Resource:1.0</supportedidentifier>
                <componentinstantiationref refid="DCE:9a5259f4-459a-4413-b1b7-db699ab45413" />
            </componentsupportedinterface>
        </connectinterface>
        <!--Connection between [Component filesource1, Port DataOut] and [Component filetee1, Port DataIn]-->
        <connectinterface id="DCE:cbf9d972-26a4-4fb1-bc49-1ea4ce94bb4a">
            <usesport>
                <usesidentifier>DataOut</usesidentifier>
                <componentinstantiationref refid="DCE:56987519-2acd-4247-ac08-ef2c6de48271" />
            </usesport>
            <providesport>
                <providesidentifier>DataIn</providesidentifier>
                <componentinstantiationref refid="DCE:9a5259f4-459a-4413-b1b7-db699ab45413" />
            </providesport>
        </connectinterface>
        <!--Connection between [Component filetee1, Port DataOut] and [Component filesink1, Port DataIn]-->
        <connectinterface id="DCE:50ca8aaa-1400-4df9-a707-22c98beedbb7">
            <usesport>
                <usesidentifier>DataOut</usesidentifier>
                <componentinstantiationref refid="DCE:9a5259f4-459a-4413-b1b7-db699ab45413" />
            </usesport>
            <providesport>
                <providesidentifier>DataIn</providesidentifier>
                <componentinstantiationref refid="DCE:8b55efc7-4625-472b-ac12-9a3594cff6a6" />
            </providesport>
        </connectinterface>
    </connections>
</softwareassembly>
