=== tloinuy/opencpi-opencv/opencpi/test/sred/rcc-file-io/output/softpkg.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!ELEMENT softpkg
      ( title?
	, author+
	, description?
	, propertyfile?
	, descriptor?
	, implementation+
	, usesdevice*
	)>
<!ATTLIST softpkg
	id		ID	#REQUIRED
	name	CDATA	#REQUIRED
	type	(sca_compliant | sca_non_compliant)  "sca_compliant"
	version	CDATA	#IMPLIED >

<!ELEMENT propertyfile
	(localfile
	)>
<!ATTLIST propertyfile
	type	CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name	CDATA	#REQUIRED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT author 
	( name*
	, company?
	, webpage?
	)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT company (#PCDATA)>

<!ELEMENT webpage (#PCDATA)>

<!ELEMENT descriptor
	(localfile
	)>
<!ATTLIST descriptor
	name	CDATA	#IMPLIED>

<!ELEMENT implementation
	( description?
	, propertyfile?
	, code
	, compiler?
	, programminglanguage?
	, humanlanguage?
	, runtime?
	, ( os | processor | dependency )+
	, usesdevice*
	)>
<!ATTLIST implementation
	id		ID	#REQUIRED
	aepcompliance (aep_compliant | aep_non_compliant) "aep_compliant">

<!ELEMENT description (#PCDATA)>

<!ELEMENT code 
	( localfile
	, entrypoint?
	, stacksize?
	, priority?
	)>
<!ATTLIST code
	type	CDATA	#IMPLIED>

<!ELEMENT entrypoint (#PCDATA)>

<!ELEMENT stacksize (#PCDATA)>

<!ELEMENT priority (#PCDATA)>

<!ELEMENT compiler EMPTY>
<!ATTLIST compiler
	name		CDATA	#REQUIRED
	version 	CDATA	#IMPLIED>

<!ELEMENT programminglanguage EMPTY>
<!ATTLIST programminglanguage
	name		CDATA	#REQUIRED
	version		CDATA	#IMPLIED>

<!ELEMENT humanlanguage EMPTY>
<!ATTLIST humanlanguage
	name		CDATA	#REQUIRED>

<!ELEMENT os EMPTY>
<!ATTLIST os
	name		CDATA	#REQUIRED
	version		CDATA	#IMPLIED>

<!ELEMENT processor EMPTY>
<!ATTLIST processor
	name		CDATA	#REQUIRED>

<!ELEMENT dependency
	( softpkgref
	| propertyref
         )>
<!ATTLIST dependency
	type		CDATA	#REQUIRED>

<!ELEMENT softpkgref
         ( localfile
         , implref?
         )>

<!ELEMENT implref EMPTY>
<!ATTLIST implref 
	refid		CDATA	#REQUIRED>

<!ELEMENT propertyref EMPTY>
<!ATTLIST propertyref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ELEMENT runtime EMPTY>
<!ATTLIST runtime
	name		CDATA	#REQUIRED
	version		CDATA	#IMPLIED>

<!ELEMENT  usesdevice
	( propertyref+
	)>
<!ATTLIST usesdevice
	id			ID		#REQUIRED
	type		CDATA	#REQUIRED>

=== tloinuy/opencpi-opencv/opencpi/test/sred/rcc-file-io/output/FileTee.spd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE softpkg SYSTEM "softpkg.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.4.6
    http://www.zeligsoft.com
-->
<softpkg id="DCE:d8d79e23-e0f6-43f7-ac14-60737cfa06dc" name="FileTee" type="sca_compliant" version="">
    <title />
    <author />
    <descriptor name="">
        <localfile name="FileTee.scd.xml" />
    </descriptor>
    <!--[Implementation FileTeeImplementation1]-->
    <implementation id="DCE:e1653438-607f-43bc-a1b6-87ff446665c2" aepcompliance="aep_compliant">
        <code type="SharedLibrary">
            <localfile name="FileTee.zip" />
            <entrypoint>FileTeeWorker</entrypoint>
        </code>
<!--
        <os name="Linux" />
        <processor name="x86" />
-->
        <dependency type="Property Reference Dependency">
            <propertyref refid="DCE:c4b738d8-fbe6-4893-81cd-1bb7a77bfb43" value="RCC" />
        </dependency>
    </implementation>
</softpkg>

=== tloinuy/opencpi-opencv/opencpi/test/sred/rcc-file-io/output/FileSink.spd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE softpkg SYSTEM "softpkg.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.4.6
    http://www.zeligsoft.com
-->
<softpkg id="DCE:f3f4a1ba-bbcf-4709-bcba-dc71b31b8c07" name="FileSink" type="sca_compliant" version="">
    <title />
    <author />
    <descriptor name="">
        <localfile name="FileSink.scd.xml" />
    </descriptor>
    <!--[Implementation FileSinkImplementation1]-->
    <implementation id="DCE:c6986861-922e-4143-b25f-675de3f74a05" aepcompliance="aep_compliant">
        <code type="SharedLibrary">
            <localfile name="FileSink.zip" />
            <entrypoint>FileSinkWorker</entrypoint>
        </code>
<!--
        <os name="Linux" />
        <processor name="x86" />
-->
        <dependency type="Property Reference Dependency">
            <propertyref refid="DCE:c4b738d8-fbe6-4893-81cd-1bb7a77bfb43" value="RCC" />
        </dependency>
    </implementation>
</softpkg>

=== tloinuy/opencpi-opencv/opencpi/test/sred/rcc-file-io/output/GenericAssemblyController.spd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE softpkg SYSTEM "softpkg.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.4.6
    http://www.zeligsoft.com
-->
<softpkg id="DCE:1dd52fca-1d51-4cc1-b4bc-daf71173b65f" name="GenericAssemblyController" type="sca_compliant" version="">
    <title />
    <author />
    <descriptor name="">
        <localfile name="GenericAssemblyController.scd.xml" />
    </descriptor>
    <!--[Implementation FileCopyAssemblyControllerImplementation1]-->
    <implementation id="DCE:cba02e8b-5358-45e1-9056-5f051f778a7f" aepcompliance="aep_compliant">
        <code type="Executable">
            <localfile name="cpi-generic-assy-controller" />
        </code>
        <os name="Linux" />
<!--
        <processor name="x86" />
-->
    </implementation>
</softpkg>

=== tloinuy/opencpi-opencv/opencpi/test/sred/rcc-file-io/output/FileSource.spd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!-- Copyright (c) 2009 Mercury Federal Systems.

This file is part of OpenCPI.

OpenCPI is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenCPI is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE softpkg SYSTEM "softpkg.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.4.6
    http://www.zeligsoft.com
-->
<softpkg id="DCE:e86d3323-bccb-438c-a142-2e84f2a0f166" name="FileSource" type="sca_compliant" version="">
    <title />
    <author />
    <descriptor name="">
        <localfile name="FileSource.scd.xml" />
    </descriptor>
    <!--[Implementation FileSourceImplementation1]-->
    <implementation id="DCE:2ad2d603-dcd4-436c-83a0-126597e66156" aepcompliance="aep_compliant">
        <code type="SharedLibrary">
            <localfile name="FileSource.zip" />
            <entrypoint>FileSourceWorker</entrypoint>
        </code>
<!--
        <os name="Linux" />
        <processor name="x86" />
-->
        <dependency type="Property Reference Dependency">
            <propertyref refid="DCE:c4b738d8-fbe6-4893-81cd-1bb7a77bfb43" value="RCC" />
        </dependency>
    </implementation>
</softpkg>
